# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentanalyze', '0002_mostcommonquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_pos', models.IntegerField(default=0)),
                ('result_neu', models.IntegerField(default=0)),
                ('result_neg', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='queryrecord',
            name='result_file',
        ),
        migrations.AddField(
            model_name='queryrecord',
            name='query_media',
            field=models.CharField(default='twitter', max_length=20),
        ),
        migrations.AddField(
            model_name='queryresult',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentanalyze.QueryRecord'),
        ),
    ]
